# Project-wide Gradle settings

# JVM memory (increase a bit for faster builds)
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Enable parallel build
org.gradle.parallel=true

# Enable build caching
org.gradle.caching=true

# Enable Gradle daemon (keeps build warm)
org.gradle.daemon=true

# ? Configuration cache (main speed boost)
org.gradle.configuration-cache=true

# Kotlin style
kotlin.code.style=official